export enum ColoresEnum {
    Blanca,
    Colorada,
    Ahumada,
    Hosca,
    Prieta,
    Baya, 
    Barana,
    Huaca,
    Huaca_Blanca,
    Huaca_Colorada,
    Huaca_Ahumada,
    Huaca_Hosca,
    Huaca_Prieta,
    Huaca_Baya, 
    Huaca_Barana,
    Careta,
}